title: "ADH - Game Client Developer"
description: "DirectX / Engine / Graphics / Debugging"
url: "https://whitecom.github.io"
baseurl: ""

remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dark"

markdown: kramdown
highlighter: rouge

head_scripts:
  - /assets/css/custom.css

timezone: Asia/Seoul

plugins:
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-sitemap

paginate: 5
paginate_path: /page:num/

enable_copy_code_button: true

search: true
search_full_content: true
search_provider: lunr

sass:
  style: compressed

collections:
  projects:
    output: true
    permalink: /projects/:path/

author:
  name: "ADH"
  bio: "Game Client Developer"
  location: "South Korea"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      sidebar:
        nav: "sidebar-nav"

  - scope:
      path: ""
      type: pages
    values:
      sidebar:
        nav: "sidebar-nav"